#! /bin/bash

# 初始化
echo -e "[$(date '+%Y-%m-%d %H:%M:%S')] 创建目录：$(pwd)/build/dist"
rm -rf ./build/dist
mkdir ./build/dist

# 拷贝
echo -e "[$(date '+%Y-%m-%d %H:%M:%S')] 复制源码..."
cp -r ./dist ./build/dist/dist
cp -r ./doc ./build/dist/doc
cp -r ./public ./build/dist/public
cp -r ./src ./build/dist/src
cp ./index.js ./build/dist/index.js
cp ./package.json ./build/dist/package.json
cp ./.npmrc ./build/dist/.npmrc

# 打包
release_file_name="release_$(date '+%y%m%d%H%M%S').zip"
release_file_path="./build/release/${release_file_name}"
echo -e "[$(date '+%Y-%m-%d %H:%M:%S')] 打包：${release_file_path}"
zip -r -q ${release_file_path} ./build/dist/.

deploy_user="root"
deploy_host="www.scyok.com"

# 上传
echo "[$(date '+%Y-%m-%d %H:%M:%S')] 上传：/mnt/www/vrender/release.zip"
scp ${release_file_path} ${deploy_user}@${deploy_host}:/mnt/www/vrender/release.zip

# 远程执行
echo "[$(date '+%Y-%m-%d %H:%M:%S')] 部署..."
ssh ${deploy_user}@${deploy_host} << remotessh
cd /mnt/www/vrender
unzip -oq release.zip
rm -f release.zip
cp -r ./build/dist/. ./
rm -rf ./build
npm install
pm2 restart all
exit
remotessh

# 清理
rm -rf ./build/dist
echo "[$(date '+%Y-%m-%d %H:%M:%S')] 完成."
